// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjWuhc2xZvUmCmbnGoU8mMGAin11LUYXs',
    appId: '1:12028514384:web:2b199f17e6d28ae8d2c155',
    messagingSenderId: '12028514384',
    projectId: 'technical-test-app',
    authDomain: 'technical-test-app.firebaseapp.com',
    storageBucket: 'technical-test-app.appspot.com',
    measurementId: 'G-T6WDSVVZLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArWe3OpSOSN3EuYBc-EPhrkrEuBVDhfVM',
    appId: '1:12028514384:android:19204cb8eccebf8ed2c155',
    messagingSenderId: '12028514384',
    projectId: 'technical-test-app',
    storageBucket: 'technical-test-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf09UpRmSq35Uo5vZWTJXeD89lyclPdbA',
    appId: '1:12028514384:ios:b16f22375687415dd2c155',
    messagingSenderId: '12028514384',
    projectId: 'technical-test-app',
    storageBucket: 'technical-test-app.appspot.com',
    iosBundleId: 'com.flutter.app.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf09UpRmSq35Uo5vZWTJXeD89lyclPdbA',
    appId: '1:12028514384:ios:f78ed88b8fdb7303d2c155',
    messagingSenderId: '12028514384',
    projectId: 'technical-test-app',
    storageBucket: 'technical-test-app.appspot.com',
    iosBundleId: 'com.flutter.app.flutterapp.RunnerTests',
  );
}
